<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBTguFPx\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBTguFPx/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBTguFPx.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBTguFPx\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBTguFPx\appAppKernelProdContainer([
    'container.build_hash' => 'BTguFPx',
    'container.build_id' => '298e4f83',
    'container.build_time' => 1721053095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBTguFPx');
